# Generated by Django 3.0 on 2020-04-27 05:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agendas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('due_date_day', models.IntegerField()),
                ('date_date_month', models.IntegerField()),
                ('date_date_year', models.IntegerField()),
                ('estimated_time_hours', models.IntegerField()),
                ('estimated_time_mins', models.IntegerField()),
                ('agenda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agendas.Agenda')),
            ],
        ),
    ]
