# Generated by Django 3.0 on 2020-04-27 05:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agendas', '0001_initial'),
        ('projects', '0002_auto_20200427_1121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='agenda',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='agendas.Agenda'),
        ),
    ]
