# Generated by Django 3.0 on 2020-04-27 05:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agendas', '0001_initial'),
        ('projects', '0003_auto_20200427_1122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='agenda',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='agendas.Agenda'),
        ),
        migrations.AlterField(
            model_name='project',
            name='date_date_month',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='date_date_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='due_date_day',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='estimated_time_hours',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='estimated_time_mins',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
