# Generated by Django 3.0 on 2020-04-27 05:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.IntegerField()),
                ('month', models.IntegerField()),
                ('year', models.IntegerField()),
                ('start_time_hours', models.IntegerField()),
                ('start_time_mins', models.IntegerField()),
                ('end_time_hours', models.IntegerField()),
                ('end_time_mins', models.IntegerField()),
                ('is_done', models.BooleanField(default=False)),
                ('is_added', models.BooleanField(default=False)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='tasks.Task')),
            ],
        ),
    ]
